#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# format js and vue files with prettier
npx --no-install prettier --write $(git diff --name-only --cached | grep -E '\.(js|vue|json)$' | xargs) 2>/dev/null || true

# stage prettier changes
git diff --name-only --cached | grep -E '\.(js|vue|json)$' | xargs -I {} git add "{}" 2>/dev/null || true
